"use client";

import { useCallback } from "react";
import { TextItem } from "@/types";

/**
 * Audio cache management. Audio is pre-generated by the local script
 * (scripts/generate.ts) and stored in Dropbox. This hook only handles
 * cache invalidation when content changes.
 */
export function useAudioCache(_items: TextItem[]) {
  const invalidate = useCallback(
    async (itemId: string) => {
      await fetch(`/api/tts/cache/${itemId}`, { method: "DELETE" });
    },
    []
  );

  return { invalidate };
}
