"use client";

import { useState, useCallback, useMemo } from "react";
import { useStorage } from "@/hooks/useStorage";
import { useTTS } from "@/hooks/useTTS";
import { TextItem } from "@/types";
import { ThemeToggle } from "@/components/ThemeToggle";
import { TextList } from "@/components/TextList";
import { AddTextModal } from "@/components/AddTextModal";
import { AddButton } from "@/components/AddButton";
import { Player } from "@/components/Player";
import { EditTextModal } from "@/components/EditTextModal";
import { Sidebar } from "@/components/Sidebar";
import { MigrateData } from "@/components/MigrateData";
import { useAudioCache } from "@/hooks/useAudioCache";

export default function Home() {
  const [migrating, setMigrating] = useState(true);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingItem, setEditingItem] = useState<TextItem | null>(null);
  const [currentItem, setCurrentItem] = useState<TextItem | null>(null);
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);
  const [selectedFolderId, setSelectedFolderId] = useState<string | null>(null);

  const { items, folders, isLoading, addItem, updateItem, deleteItem, getItem, addFolder, updateFolder, deleteFolder, refresh } = useStorage();

  // Audio cache management (audio is pre-generated by local script)
  useAudioCache(items);

  const filteredItems = useMemo(() => {
    if (selectedFolderId === null) return items;
    if (selectedFolderId === "unfiled") return items.filter((item) => !item.folderId);
    return items.filter((item) => item.folderId === selectedFolderId);
  }, [items, selectedFolderId]);

  const selectedFolderName = useMemo(() => {
    if (selectedFolderId === null) return null;
    if (selectedFolderId === "unfiled") return "Unfiled";
    return folders.find((f) => f.id === selectedFolderId)?.name ?? null;
  }, [selectedFolderId, folders]);

  const handleProgressUpdate = useCallback(
    (id: string, progress: number, position: number) => {
      updateItem(id, { progress, lastPosition: position });
    },
    [updateItem]
  );

  const handleEnd = useCallback(
    (id: string) => {
      updateItem(id, { progress: 100, lastPosition: 0 });
      setCurrentItem(null);
    },
    [updateItem]
  );

  const tts = useTTS({
    onProgressUpdate: handleProgressUpdate,
    onEnd: handleEnd,
  });

  const handlePlay = useCallback(
    async (item: TextItem) => {
      const freshItem = await getItem(item.id);
      if (freshItem) {
        setCurrentItem(freshItem);
        tts.toggle(freshItem);
      }
    },
    [getItem, tts]
  );

  const handleToggle = useCallback(() => {
    if (currentItem) {
      tts.toggle(currentItem);
    }
  }, [currentItem, tts]);

  const handleStop = useCallback(() => {
    tts.stop();
    setCurrentItem(null);
  }, [tts]);

  const handleDelete = useCallback(
    async (id: string) => {
      if (currentItem?.id === id) {
        tts.stop();
        setCurrentItem(null);
      }
      await deleteItem(id);
    },
    [currentItem, tts, deleteItem]
  );

  const handleAddText = useCallback(
    async (title: string, content: string, folderId?: string) => {
      await addItem(title, content, folderId);
    },
    [addItem]
  );

  const handleItemClick = useCallback(
    async (item: TextItem) => {
      const freshItem = await getItem(item.id);
      if (freshItem) {
        setEditingItem(freshItem);
      }
    },
    [getItem]
  );

  const handleSaveItem = useCallback(
    async (id: string, title: string, content: string) => {
      await updateItem(id, { title, content });
      const freshItem = await getItem(id);
      if (freshItem) {
        setEditingItem(freshItem);
      }
    },
    [updateItem, getItem]
  );

  const handleDeleteFromEdit = useCallback(
    async (id: string) => {
      if (currentItem?.id === id) {
        tts.stop();
        setCurrentItem(null);
      }
      await deleteItem(id);
      setEditingItem(null);
    },
    [currentItem, tts, deleteItem]
  );

  const handlePlayFromEdit = useCallback(
    async (item: TextItem) => {
      const freshItem = await getItem(item.id);
      if (freshItem) {
        setCurrentItem(freshItem);
        tts.toggle(freshItem);
        setEditingItem(freshItem);
      }
    },
    [getItem, tts]
  );

  const handleAddFolder = useCallback(
    async (name: string) => {
      await addFolder(name);
    },
    [addFolder]
  );

  const handleRenameFolder = useCallback(
    async (id: string, name: string) => {
      await updateFolder(id, { name });
    },
    [updateFolder]
  );

  const handleDeleteFolder = useCallback(
    async (id: string) => {
      if (selectedFolderId === id) {
        setSelectedFolderId(null);
      }
      await deleteFolder(id);
    },
    [deleteFolder, selectedFolderId]
  );

  return (
    <div className="flex flex-col h-screen max-w-3xl mx-auto">
      {migrating && <MigrateData onDone={() => { setMigrating(false); refresh(); }} />}
      <header className="flex items-center justify-between p-4 border-b border-border">
        <div className="flex items-center gap-2">
          <button
            onClick={() => setIsSidebarOpen(true)}
            className="p-2 hover:bg-card rounded-lg transition-colors"
            aria-label="Open folders"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
            </svg>
          </button>
          <h1 className="text-xl font-bold">{selectedFolderName ?? "Talkie"}</h1>
        </div>
        <div className="flex items-center gap-2">
          {currentItem && (
            <button
              onClick={handleStop}
              className="p-2 hover:bg-card rounded-lg transition-colors text-muted"
              aria-label="Stop playback"
            >
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          )}
          <ThemeToggle />
        </div>
      </header>

      {isLoading ? (
        <div className="flex-1 flex items-center justify-center">
          <div className="w-8 h-8 border-2 border-accent border-t-transparent rounded-full animate-spin" />
        </div>
      ) : (
        <TextList
          items={filteredItems}
          folders={folders}
          showFolderBadge={selectedFolderId === null}
          currentPlayingId={tts.currentItemId}
          isPlaying={tts.isPlaying}
          onPlay={handlePlay}
          onDelete={handleDelete}
          onItemClick={handleItemClick}
        />
      )}

      <AddButton onClick={() => setIsModalOpen(true)} isPlayerVisible={!!currentItem} />

      <AddTextModal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        onAdd={handleAddText}
        folders={folders}
        defaultFolderId={selectedFolderId === "unfiled" ? undefined : selectedFolderId ?? undefined}
      />

      <Player
        currentItem={currentItem}
        isPlaying={tts.isPlaying}
        isLoading={tts.isLoading}
        progress={tts.progress}
        onToggle={handleToggle}
      />

      <EditTextModal
        item={editingItem}
        isPlaying={tts.isPlaying && tts.currentItemId === editingItem?.id}
        currentPosition={
          tts.isPlaying && tts.currentItemId === editingItem?.id
            ? tts.currentPosition
            : 0
        }
        onClose={() => setEditingItem(null)}
        onSave={handleSaveItem}
        onDelete={handleDeleteFromEdit}
        onPlay={handlePlayFromEdit}
      />

      <Sidebar
        isOpen={isSidebarOpen}
        onClose={() => setIsSidebarOpen(false)}
        folders={folders}
        items={items}
        selectedFolderId={selectedFolderId}
        onSelectFolder={setSelectedFolderId}
        onAddFolder={handleAddFolder}
        onRenameFolder={handleRenameFolder}
        onDeleteFolder={handleDeleteFolder}
      />
    </div>
  );
}
